### ISSUE TITLE
Use YAML instead of custom syntax

### ISSUE THREAD

**Issue by Defman21** [Defman21/komodo-locale-gen#1]

**Comment by Defman21** [comment]
Simple example provided by @Naatan
```yaml
-
chrome://komodo/locale/library.properties:
    incrementalSearchPrompt: Interactive Search: %S
    incrementalSearchStopped: Interactive Search Stopped: %S
    noOccurencesFound: No occurrences of %S found.
    findNotFound: #1 occurrence was found.;#1 occurrences were found.
    numberOfRepeats: Number of Repeats: %S|
    searchCanceled: Search canceled.
-
chrome://komodo/locale/scc.dtd:
   	F.accesskey: F
	H.accesskey: H
	M.accesskey: M
```
